"""Initial migration.

Revision ID: 40dcacf7189b
Revises: 
Create Date: 2025-06-25 23:06:49.842076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40dcacf7189b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('area_atuacao', sa.String(length=100), nullable=True),
    sa.Column('disponibilidade', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('laboratorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('recursos', sa.JSON(), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('laboratorio', sa.String(length=50), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('horarios', sa.JSON(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocupacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('curso_evento', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('grupo_ocupacao_id', sa.String(length=36), nullable=True),
    sa.Column('tipo_ocupacao', sa.String(length=50), nullable=True),
    sa.Column('recorrencia', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocupacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocupacoes_grupo_ocupacao_id'), ['grupo_ocupacao_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('refresh_tokens')
    with op.batch_alter_table('ocupacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocupacoes_grupo_ocupacao_id'))

    op.drop_table('ocupacoes')
    op.drop_table('agendamentos')
    op.drop_table('usuarios')
    op.drop_table('turmas')
    op.drop_table('salas')
    op.drop_table('laboratorios')
    op.drop_table('instrutores')
    # ### end Alembic commands ###
